examenParcial/examenParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestionTienda/', include('gestionTienda.urls')),
]

examenParcial/gestionTienda/urls.py
from django.urls import path
from . import views
app_name = 'gestionTienda'

urlpatterns = [
    path('productos', views.productos, name = 'productos'),
    path('tiendas', views.tiendas, name = 'tiendas'),
    path('detalleTienda/<str:idTienda>', views.detalleTienda, name = 'detalleTienda'),
    path('eliminarTienda/<str:idTienda>', views.eliminarTienda, name = 'eliminarTienda'),
    path('eliminarProducto/<str:idProducto>', views.eliminarProducto, name = 'eliminarProducto'),
    path('eliminarProductoTienda/<str:idProducto>/<str:idTienda>', views.eliminarProductoTienda, name = 'eliminarProductoTienda'),

]

examenParcial/gestionTienda/models.py
from django.db import models

# Create your models here.

class infoTienda(models.Model):
    Direccion = models.CharField(max_length=32, blank=True, null=True)
    Provincia = models.CharField(max_length=32, blank=True, null=True)
    Region = models.CharField(max_length=32, blank=True, null=True)
    Fecha_creacion = models.CharField(max_length=32, blank=True, null=True)
    Telefono_contacto = models.CharField(max_length=32, blank=True, null=True)

class infoProducto(models.Model):
    Codigo = models.CharField(max_length=32, blank=True, null=True)
    Descripcion = models.CharField(max_length=32, blank=True, null=True)
    Precio_venta = models.CharField(max_length=32, blank=True, null=True)
    Cantidad = models.CharField(max_length=32, blank=True, null=True)
    Tienda_relacionada = models.OneToOneField(infoTienda, on_delete=models.SET_NULL, null=True, blank=True)

examenParcial/gestionTienda/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import infoTienda, infoProducto

# Create your views here.
def productos(request):
    if request.method == 'POST':
        codProducto = request.POST.get('cod_producto')
        desProducto = request.POST.get('des_producto')
        preProducto = request.POST.get('pre_producto')
        cantProducto = request.POST.get('cant_producto')
        selProducto = request.POST.get('sel_producto')
        infoProducto.objects.create(
            Codigo = codProducto,
            Descripcion = desProducto,
            Precio_venta = preProducto,
            Cantidad = cantProducto)
        return HttpResponseRedirect(reverse('gestionTienda:productos'))
    return render(request, 'gestionProductos.html', {
        'listaProductos': infoProducto.objects.all().order_by('id'),
        'listarTiendas': infoTienda.objects.all().order_by('id')
    })
def detalleTienda(request, idTienda):
    tienda = infoTienda.objects.get(id = idTienda)
    if request.method == 'POST':
        idProducto = request.POST.get('sel_Producto')
        infoProducto.objects.filter(id = idProducto).update(Tienda_relacionada = tienda.id)
    listaProductos = infoProducto.objects.all().order_by('id')
    productosTienda = infoProducto.objects.filter(Tienda_relacionada = tienda.id)
    return render(request, 'detalleTienda.html', {
        'listaProductosTienda': productosTienda.order_by('id'),
        'tienda': tienda,
        'listaProductos': listaProductos
    })

def tiendas(request):
    if request.method == 'POST':
        dirTienda = request.POST.get('dir_Tienda')
        proTienda = request.POST.get('pro_Tienda')
        regTienda = request.POST.get('reg_Tienda')
        fecCreaTienda = request.POST.get('fec_Tienda')
        telTienda = request.POST.get('tel_Tienda')
        infoTienda.objects.create(
            Direccion = dirTienda,
            Provincia = proTienda,
            Region = regTienda,
            Fecha_creacion = fecCreaTienda,
            Telefono_contacto = telTienda)
        return HttpResponseRedirect(reverse('gestionTienda:tiendas'))
    return render(request, 'gestionTiendas.html', {
        'listaTiendas': infoTienda.objects.all().order_by('id')
    })
def eliminarTienda(request, idTienda):
    tiendaEliminar = infoTienda.objects.get(id = idTienda)
    tiendaEliminar.delete()
    return render(request, 'gestionTiendas.html', {
        'listarTiendas': infoTienda.objects.all().order_by('id')
    })

def eliminarProducto(request, idProducto):
    productoEliminar = infoProducto.objects.get(id = idProducto)
    productoEliminar.delete()
    return render(request, 'gestionProductos.html', {
        'listaProductos': infoProducto.objects.all().order_by('id'),
        'listarTiendas': infoTienda.objects.all().order_by('id')
    })

def eliminarProductoTienda(request, idProducto, idTienda):
    productoQuitar = infoProducto.objects.get(id = idProducto)
    tienda = infoTienda.objects.get(id = idTienda)
    productoQuitar.Tienda_relacionada = None
    productoQuitar.save()
    listaProductos = infoProducto.objects.all().order_by('id')
    productosTienda = infoProducto.objects.filter(Tienda_relacionada = tienda.id)
    return render(request, 'detalleTienda.html', {
        'listaProductosTienda': productosTienda.order_by('id'),
        'tienda': tienda,
        'listaProductos': listaProductos
    })

examenParcial/gestionTienda/templates/detalleTienda.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Detalle de la Tienda : {{ tienda.id }}</title>
    <!-- <link rel="stylesheet" href="{% static 'index.css' %}"> -->
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body>
    <div class="container py-3">
      <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a
                    class="nav-link active"
                    aria-current="page"
                    href="{% url 'gestionTienda:tiendas' %}"
                    >Tiendas</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'gestionTienda:productos' %}"
                    >Productos</a
                  >
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <div class="row">
          <div class="col-9">
            <h2 class="h2 text-bold">Tiendas</h2>
          </div>
          <div class="col-3">
            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modal_Nuevo">Añadir Producto</button>
          </div>
        </div>
        <div class="row">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Código</th>
                <th scope="col">Descripción</th>
                <th scope="col">Precio Venta</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Remover</th>
              </tr>
            </thead>
            <tbody>
              {% for producto in listaProductosTienda %}
              <tr>
                <td>{{ producto.Codigo }}</td>
                <td>{{ producto.Descripcion }}</td>
                <td>{{ producto.Precio_venta }}</td>
                <td>{{ producto.Cantidad }}</td>
                <td>
                  <a type="button" class="btn btn-danger" href="{% url 'gestionTienda:eliminarProductoTienda' idProducto=producto.id idTienda=tienda.id %}">X</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </main>
<!-- Modal Nuevo -->
<div class="modal fade" id="modal_Nuevo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="post" action="{% url 'gestionTienda:detalleTienda' tienda.id %}">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Añadir Producto</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          {% csrf_token %}
          <div>
            <label for="sel_Producto" class="form-label">Producto:</label>
            <select type="text" name="sel_Producto" class="form-control" required>
              <option value="" disabled selected>Seleccione...</option>
              {% for produ in listaProductos %}
              <option value="{{produ.id}}">{{produ.Descripcion}}</option>
              {% endfor %}
            </select>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    </form>
    </div>
  </div>
</div>
  </body>
</html>

examenParcial/gestionTienda/templates/gestionProductos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gestión Tienda</title>
    <!-- <link rel="stylesheet" href="{% static 'index.css' %}"> -->
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body>
    <div class="container py-3">
      <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a
                    class="nav-link "
                    aria-current="page"
                    href="{% url 'gestionTienda:tiendas' %}"
                    >Tiendas</a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'gestionTienda:productos' %}"
                    >Productos</a
                  >
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <div class="row">
          <div class="col-9">
            <h2 class="h2 text-bold">Productos</h2>
          </div>
          <div class="col-3">
            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modal_Nuevo">Nuevo Producto</button>
          </div>
        </div>
        <div class="row">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Codigo</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Precio_venta</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Tienda_Relacionada</th>
                <th scope="col">Acciones</th>
              </tr>
            </thead>
            <tbody>
              {% for producto in listaProductos %}
              <tr>
                <td>{{ producto.Codigo }}</td>
                <td>{{ producto.Descripcion }}</td>
                <td>{{ producto.Precio_venta }}</td>
                <td>{{ producto.Cantidad }}</td>
                <td>{{ producto.Tienda_relacionada }}</td>
                <td>
                  <a type="button" class="btn btn-danger" href="{% url 'gestionTienda:eliminarProducto' producto.id %}">Eliminar</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </main>
<!-- Modal Nuevo -->
<div class="modal fade" id="modal_Nuevo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="post" action="{% url 'gestionTienda:productos' %}">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Producto</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          {% csrf_token %}
          <div>
            <label for="cod_producto" class="form-label">Código del Producto:</label>
            <input type="text" name="cod_producto" class="form-control" required/>
          </div>
          <div>
            <label for="des_producto" class="form-label">Descripción:</label>
            <input id="desProducto" type="text" name="des_producto" class="form-control" required/>
          </div>
          <div>
            <label for="pre_producto" class="form-label">Precio:</label>
            <input id="preProducto" type="text" name="pre_producto" class="form-control" required/>
          </div>
          <div>
            <label for="cant_producto" class="form-label">Cantidad:</label>
            <input id="cantProducto" type="number" name="cant_producto" class="form-control" required/>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    </form>
    </div>
  </div>
</div>
  </body>
</html>

examenParcial/gestionTienda/templates/gestionTiendas.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gestión Tienda</title>
    <!-- <link rel="stylesheet" href="{% static 'index.css' %}"> -->
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body>
    <div class="container py-3">
      <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a
                    class="nav-link active"
                    aria-current="page"
                    href="{% url 'gestionTienda:tiendas' %}"
                    >Tiendas</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'gestionTienda:productos' %}"
                    >Productos</a
                  >
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <div class="row">
          <div class="col-9">
            <h2 class="h2 text-bold">Tiendas</h2>
          </div>
          <div class="col-3">
            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modal_Nuevo">Nueva Tienda</button>
          </div>
        </div>
        <div class="row">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Direccion</th>
                <th scope="col">Provincia</th>
                <th scope="col">Region</th>
                <th scope="col">Fecha</th>
                <th scope="col">Teléfono</th>
                <th scope="col">Acciones</th>
              </tr>
            </thead>
            <tbody>
              {% for tienda in listaTiendas %}
              <tr>
                <td>{{ tienda.Direccion }}</td>
                <td>{{ tienda.Provincia }}</td>
                <td>{{ tienda.Region }}</td>
                <td>{{ tienda.Fecha_creacion }}</td>
                <td>{{ tienda.Telefono_contacto }}</td>
                <td>
                  <div class="btn-group" role="group">
                    <a type="button" class="btn btn-primary" href="{% url 'gestionTienda:detalleTienda' tienda.id %}">ver Productos</a>
                    <a type="button" class="btn btn-danger" href="{% url 'gestionTienda:eliminarTienda' tienda.id %}">Eliminar</a>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </main>
<!-- Modal Nuevo -->
<div class="modal fade" id="modal_Nuevo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="post" action="{% url 'gestionTienda:tiendas' %}">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Registrar Tienda</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          {% csrf_token %}
          <div>
            <label for="dir_Tienda" class="form-label">Dirección de la Tienda:</label>
            <input type="text" name="dir_Tienda" class="form-control" required/>
          </div>
          <div>
            <label for="pro_Tienda" class="form-label">Provincia de Origen:</label>
            <input id="nombreInfo" type="text" name="pro_Tienda" class="form-control" required/>
          </div>
          <div>
            <label for="reg_Tienda" class="form-label">Región de Origen:</label>
            <input id="nombreInfo" type="text" name="reg_Tienda" class="form-control" required/>
          </div>
          <div>
            <label for="fec_Tienda" class="form-label">Fecha de Origen:</label>
            <input id="nombreInfo" type="date" name="fec_Tienda" class="form-control" required/>
          </div>
          <div>
            <label for="tel_Tienda" class="form-label">Teléfono de Tienda:</label>
            <input id="nombreInfo" type="number" name="tel_Tienda" class="form-control" required/>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    </form>
    </div>
  </div>
</div>
  </body>
</html>